name: My First GitHub Actions

on: [push]

env:
  DOCKER_IMAGE: deepakrao2323/diabetes-demo   # Your DockerHub repo
  DOCKER_TAG: v1                              # or latest, or dynamic
  
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.8, 3.9]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
    
    - name: DockerHub Login
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 5: Build and push Docker image
    - name: Build and Push Docker image
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        tags: ${{ env.DOCKER_IMAGE }}:${{ env.DOCKER_TAG }}

      # Step 6: Verify Docker Image (optional)
    - name: Verify Image Pull
      run: docker pull ${{ env.DOCKER_IMAGE }}:${{ env.DOCKER_TAG }}
    
